name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
  Explore-GitHub-Actions-Second-Job:
    runs-on: arc-runner-set
    steps:
    - run: echo "🎉 This job uses runner scale set runners!! second JOB"
  Build-rust:
    runs-on: arc-runner-set
    steps:

    - name: install rust 
      run: |
        apt install curl build-essential libssl-dev -y
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    - name: build rust
      run: |
        cd rust-project
        cargo build
        cargo run