name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Hello-Scott:
    runs-on: arc-runner-set
    steps:
      - run: echo "🎉 Hey Scott!! from the pod-1!"
  Hello-Joe:
    runs-on: arc-runner-set
    steps:
      - run: echo "🎉 Hey Joe!! from pod-2"
  Rust-Install:
    runs-on: arc-runner-set
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install curl
        run: |
          sudo apt-get update 
          sudo apt-get install -y curl
          sudo apt-get install -y build-essential

      - name: Set up Rust
        uses: actions-rs/toolchain@v2
        with:
          toolchain: stable
          override: true

      - name: Build project
        run: |
          ls
          cd rust-project
          cargo update 
          cargo build

      - name: Run tests
        run: |
          ls
          cd rust-project  
          cargo test
  Angular-Install:
    runs-on: arc-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt update
          sudo apt-get install -y nodejs npm

      - name: Verify Node.js installation
        run: |
          node -v
          npm -v
      - name: Install Angular CLI
        run: sudo npm install -g @angular/cli -y
  Hello-Doug:
    runs-on: arc-runner-set
    needs: Hello-Joe
    steps:
      - run: |
          echo "🎉  Hey Doug!! from the pod-5!"
  Hello-Clark:
    runs-on: arc-runner-set
    needs: Hello-Joe
    steps:
      - run: |
          echo "🎉  Hey Clark!! from the pod-5!"
  Hello-KG:
    runs-on: arc-runner-set
    needs: Hello-Doug
    steps:
      - run: |
          echo "🎉  Hey KG!! from the pod-5!"
  Hello-Dave:
    runs-on: arc-runner-set
    needs: Hello-Joe
    steps:
      - run: |
          echo "🎉  Hey Dave!! from the new pod!"
  Hello-DPT:
    runs-on: arc-runner-set
    needs: Hello-Scott
    steps:
      - run: |
          echo "🎉  Hey Team!! from the another new pod!"