name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: arc-runner-set
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
  Explore-GitHub-Actions-Second-Job:
    runs-on: arc-runner-set
    steps:
    - run: echo "🎉 This job uses runner scale set runners!! second JOB"
  Build-rust:
    runs-on: arc-runner-set
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install curl
      run: |
        sudo apt-get update 
        sudo apt-get install -y curl
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
  
    - name: Verify Rust installation
      run: rustc --version

    - name: Cache Cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-registry-

    - name: Cache Cargo index
      uses: actions/cache@v2
      with:
        path: ~/.cargo/index
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-index-

    - name: Build project
      run: |
        ls
        cd rust-project
        sudo apt update
        sudo apt install build-essential
        cargo update 
        cargo build

    - name: Run tests
      run: |
        ls
        cd rust-project  
        cargo test
  
  Build-UI:
    runs-on: arc-runner-set

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      run: |
        curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Verify Node.js installation
      run: |
        node -v
        npm -v
    
    - name: Install Angular CLI
      run: sudo npm install -g @angular/cli

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Build application
      run: npm run build