name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: arc-runner-set
    steps:
      - run: echo "🎉 This job uses runner scale set runners!"
  Explore-GitHub-Actions-Second-Job:
    runs-on: arc-runner-set
    steps:
      - run: echo "🎉 Just Showing the ARC capabilities"
  Build-rust:
    runs-on: arc-runner-set
    needs: Explore-GitHub-Actions-Second-Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install curl
        run: |
          sudo apt-get update 
          sudo apt-get install -y curl

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build project
        run: |
          ls
          cd rust-project
          cargo update 
          cargo build

      - name: Run tests
        run: |
          ls
          cd rust-project  
          cargo test
  Angular-Install:
    runs-on: arc-runner-set
    needs: Explore-GitHub-Actions-Second-Job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install curl
        run: |
          sudo apt-get update 
          sudo apt-get install -y curl
          sudo apt-get install -y build-essential

      - name: Install Node.js
        run: |
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt update
          sudo apt-get install -y nodejs npm

      - name: Verify Node.js installation
        run: |
          node -v
          npm -v
      - name: Install Angular CLI
        run: sudo npm install -g @angular/cli -y
  Running-job-to-show-different-pods:
    runs-on: arc-runner-set
    needs: Explore-GitHub-Actions-Second-Job
    steps:
      - run: |
          echo "🎉 This job uses runner scale set runners!"
          sleep
  Running-job-to-show-different-pods-again:
    runs-on: arc-runner-set
    needs: Explore-GitHub-Actions-Second-Job
    steps:
      - run: |
          echo "🎉 This job uses runner scale set runners!"
          sleep 30